export { default as HrmsDashboard } from "./HrmsDashboard"
export { default as Employees } from "../employees/pages/Employees"
export { default as EmployeeDetail } from "../employees/pages/EmployeeDetail"
export { default as Attendance } from "../attendance/pages/Attendance"
export { default as Leave } from "../leave/pages/Leave"
export { default as Payroll } from "../payroll/pages/Payroll"
export { default as PayrollDetail } from "../payroll/pages/PayrollDetail"
